name: coffee_shop
description: "A test assignment for student labs"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.2
  logger: ^2.5.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  go_router: ^15.1.2
  retrofit: ^4.4.2
  envied: ^1.1.1
  freezed_annotation: ^3.0.0

  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.33
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_displaymode: ^0.6.0
  scrollable_positioned_list: ^0.3.8
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  freezed: ^3.0.6

  drift_dev: ^2.26.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/sun.png
    - assets/images/moon.png
    - assets/images/cart_shopping.png
    - assets/images/coffee_error.png
    - assets/images/back.png

    - assets/fonts/open_sans.ttf
    - assets/fonts/open_sans_regular.ttf
    - assets/fonts/open_sans_semi_bold.ttf
